# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_weibullanalyse.ui'
#
# Created by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ValueWidgetBase(object):
    def setupUi(self, ValueWidgetBase):
        ValueWidgetBase.setObjectName(_fromUtf8("ValueWidgetBase"))
        ValueWidgetBase.resize(366, 560)
        ValueWidgetBase.setMinimumSize(QtCore.QSize(366, 560))
        ValueWidgetBase.setMaximumSize(QtCore.QSize(366, 560))
        self.verticalLayout = QtGui.QVBoxLayout(ValueWidgetBase)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_4 = QtGui.QLabel(ValueWidgetBase)
        self.label_4.setMinimumSize(QtCore.QSize(0, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_9.addWidget(self.label_4)
        self.InRastC = QtGui.QComboBox(ValueWidgetBase)
        self.InRastC.setMinimumSize(QtCore.QSize(200, 30))
        self.InRastC.setObjectName(_fromUtf8("InRastC"))
        self.horizontalLayout_9.addWidget(self.InRastC)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_3 = QtGui.QLabel(ValueWidgetBase)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        self.InRastK = QtGui.QComboBox(ValueWidgetBase)
        self.InRastK.setMinimumSize(QtCore.QSize(200, 30))
        self.InRastK.setObjectName(_fromUtf8("InRastK"))
        self.horizontalLayout_7.addWidget(self.InRastK)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_6 = QtGui.QLabel(ValueWidgetBase)
        self.label_6.setMinimumSize(QtCore.QSize(0, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_10.addWidget(self.label_6)
        self.InRastW = QtGui.QComboBox(ValueWidgetBase)
        self.InRastW.setMinimumSize(QtCore.QSize(200, 30))
        self.InRastW.setObjectName(_fromUtf8("InRastW"))
        self.horizontalLayout_10.addWidget(self.InRastW)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_7 = QtGui.QLabel(ValueWidgetBase)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_6.addWidget(self.label_7)
        self.InRastZ = QtGui.QComboBox(ValueWidgetBase)
        self.InRastZ.setMinimumSize(QtCore.QSize(200, 30))
        self.InRastZ.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.InRastZ.setObjectName(_fromUtf8("InRastZ"))
        self.horizontalLayout_6.addWidget(self.InRastZ)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cbxActive = QtGui.QCheckBox(ValueWidgetBase)
        self.cbxActive.setMinimumSize(QtCore.QSize(0, 20))
        self.cbxActive.setObjectName(_fromUtf8("cbxActive"))
        self.horizontalLayout_4.addWidget(self.cbxActive)
        self.cbxGraph = QtGui.QCheckBox(ValueWidgetBase)
        self.cbxGraph.setMinimumSize(QtCore.QSize(0, 20))
        self.cbxGraph.setStatusTip(_fromUtf8(""))
        self.cbxGraph.setObjectName(_fromUtf8("cbxGraph"))
        self.horizontalLayout_4.addWidget(self.cbxGraph)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(ValueWidgetBase)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.dataName = QtGui.QLineEdit(ValueWidgetBase)
        self.dataName.setPlaceholderText(_fromUtf8(""))
        self.dataName.setObjectName(_fromUtf8("dataName"))
        self.horizontalLayout_5.addWidget(self.dataName)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.line_2 = QtGui.QFrame(ValueWidgetBase)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_3.addWidget(self.line_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_11 = QtGui.QLabel(ValueWidgetBase)
        self.label_11.setMinimumSize(QtCore.QSize(0, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_11.addWidget(self.label_11)
        self.bufferz0 = QtGui.QSpinBox(ValueWidgetBase)
        self.bufferz0.setMinimumSize(QtCore.QSize(0, 30))
        self.bufferz0.setMaximumSize(QtCore.QSize(16777215, 33))
        self.bufferz0.setMinimum(0)
        self.bufferz0.setMaximum(10000)
        self.bufferz0.setSingleStep(100)
        self.bufferz0.setProperty("value", 1500)
        self.bufferz0.setObjectName(_fromUtf8("bufferz0"))
        self.horizontalLayout_11.addWidget(self.bufferz0)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(ValueWidgetBase)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 33))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.outputXEdit = QtGui.QTextEdit(ValueWidgetBase)
        self.outputXEdit.setMinimumSize(QtCore.QSize(0, 33))
        self.outputXEdit.setMaximumSize(QtCore.QSize(16777215, 33))
        self.outputXEdit.setObjectName(_fromUtf8("outputXEdit"))
        self.horizontalLayout.addWidget(self.outputXEdit)
        self.label = QtGui.QLabel(ValueWidgetBase)
        self.label.setMaximumSize(QtCore.QSize(16777215, 33))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.outputYEdit = QtGui.QTextEdit(ValueWidgetBase)
        self.outputYEdit.setMinimumSize(QtCore.QSize(0, 33))
        self.outputYEdit.setMaximumSize(QtCore.QSize(16777215, 33))
        self.outputYEdit.setObjectName(_fromUtf8("outputYEdit"))
        self.horizontalLayout.addWidget(self.outputYEdit)
        self.buttonSaveAs = QtGui.QPushButton(ValueWidgetBase)
        self.buttonSaveAs.setMinimumSize(QtCore.QSize(129, 33))
        self.buttonSaveAs.setMaximumSize(QtCore.QSize(16777215, 33))
        self.buttonSaveAs.setObjectName(_fromUtf8("buttonSaveAs"))
        self.horizontalLayout.addWidget(self.buttonSaveAs)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.graphControls = QtGui.QWidget(ValueWidgetBase)
        self.graphControls.setObjectName(_fromUtf8("graphControls"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.graphControls)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout.addWidget(self.graphControls)
        self.stackedWidget = QtGui.QStackedWidget(ValueWidgetBase)
        self.stackedWidget.setMinimumSize(QtCore.QSize(350, 300))
        self.stackedWidget.setMaximumSize(QtCore.QSize(350, 350))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tableWidget = QtGui.QTableWidget(self.page)
        self.tableWidget.setMinimumSize(QtCore.QSize(350, 300))
        self.tableWidget.setMaximumSize(QtCore.QSize(350, 300))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.stackedWidget.addWidget(self.page)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(ValueWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(ValueWidgetBase)

    def retranslateUi(self, ValueWidgetBase):
        ValueWidgetBase.setWindowTitle(_translate("ValueWidgetBase", "Form", None))
        self.label_4.setText(_translate("ValueWidgetBase", "Weibullparameter (C)", None))
        self.label_3.setText(_translate("ValueWidgetBase", "Weibullparameter (K)", None))
        self.label_6.setText(_translate("ValueWidgetBase", "Weibullparameter (W)", None))
        self.label_7.setText(_translate("ValueWidgetBase", "Rauhigkeitslayer (z0)", None))
        self.cbxActive.setToolTip(_translate("ValueWidgetBase", "(Shift+A) to toggle", None))
        self.cbxActive.setText(_translate("ValueWidgetBase", "Start/Stop", None))
        self.cbxGraph.setToolTip(_translate("ValueWidgetBase", "(Shift+W) to toggle", None))
        self.cbxGraph.setText(_translate("ValueWidgetBase", "Weibull", None))
        self.label_5.setText(_translate("ValueWidgetBase", "Standort", None))
        self.dataName.setToolTip(_translate("ValueWidgetBase", "Name des Standortes angeben", None))
        self.dataName.setText(_translate("ValueWidgetBase", "Standort", None))
        self.label_11.setText(_translate("ValueWidgetBase", "Radius (z0)", None))
        self.label_2.setText(_translate("ValueWidgetBase", "X", None))
        self.label.setText(_translate("ValueWidgetBase", "Y", None))
        self.buttonSaveAs.setToolTip(_translate("ValueWidgetBase", "(Shift+S) to Save Graph", None))
        self.buttonSaveAs.setText(_translate("ValueWidgetBase", "Grafik Speichern", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ValueWidgetBase", "Layer", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ValueWidgetBase", "Value", None))

